-- Grundschultag Anmeldung – Schema für MariaDB 11
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS settings (
    setting_key VARCHAR(100) NOT NULL PRIMARY KEY,
    setting_value TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fachbereiche (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    teaser_text TEXT NULL,
    teaser_bild VARCHAR(255) NULL,
    aktiv TINYINT(1) NOT NULL DEFAULT 1,
    sortierung INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schienen (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fachbereich_id INT UNSIGNED NOT NULL,
    name VARCHAR(200) NOT NULL,
    kapazitaet INT UNSIGNED NOT NULL DEFAULT 20,
    sortierung INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_schienen_fachbereich
        FOREIGN KEY (fachbereich_id) REFERENCES fachbereiche(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS anmeldungen (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    schiene_id INT UNSIGNED NOT NULL,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(255) NOT NULL,
    token CHAR(64) NOT NULL UNIQUE,
    status ENUM('aktiv', 'storniert') NOT NULL DEFAULT 'aktiv',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at DATETIME NULL,
    CONSTRAINT fk_anmeldungen_schiene
        FOREIGN KEY (schiene_id) REFERENCES schienen(id) ON DELETE RESTRICT,
    INDEX idx_anmeldungen_schiene_status (schiene_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
